# Cloud Build config for deploying to Cloud Run
# Builds container and deploys as both Service and Job

steps:
  # Build the container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/anyror-scraper', '.']
  
  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/anyror-scraper']
  
  # Deploy Cloud Run Service (API)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'anyror-api'
      - '--image=gcr.io/$PROJECT_ID/anyror-scraper'
      - '--region=asia-south1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=3'
      - '--timeout=300'
      - '--set-env-vars=GEMINI_API_KEY=${_GEMINI_API_KEY}'
  
  # Create Cloud Run Job (for batch processing)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'jobs'
      - 'create'
      - 'anyror-district-search'
      - '--image=gcr.io/$PROJECT_ID/anyror-scraper'
      - '--region=asia-south1'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--task-timeout=3600'
      - '--max-retries=1'
      - '--parallelism=34'
      - '--tasks=34'
      - '--set-env-vars=GEMINI_API_KEY=${_GEMINI_API_KEY}'
      - '--command=python,job_runner.py'

substitutions:
  _GEMINI_API_KEY: ''

images:
  - 'gcr.io/$PROJECT_ID/anyror-scraper'
